# Generated by Django 5.2 on 2025-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='alumni')),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inquiries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('course_studied', models.TextField(max_length=300)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhyStayConnected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='alumni')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
