# Generated by Django 5.2 on 2025-05-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alumnimessage_delete_inquiries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whystayconnected',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
