# Generated by Django 5.2 on 2025-06-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_whystayconnected_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Alumni Contacts',
                'db_table': 'alumni_contacts',
            },
        ),
        migrations.AlterModelOptions(
            name='alumni',
            options={'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='alumniboard',
            options={'verbose_name_plural': 'Alumni Board'},
        ),
        migrations.AlterModelOptions(
            name='alumnimessage',
            options={'verbose_name_plural': 'Alumni Message'},
        ),
        migrations.AlterModelOptions(
            name='whystayconnected',
            options={'verbose_name_plural': 'Why Stay Connected'},
        ),
        migrations.AlterModelTable(
            name='alumni',
            table='alumni',
        ),
        migrations.AlterModelTable(
            name='alumniboard',
            table='alumni_board',
        ),
        migrations.AlterModelTable(
            name='alumnimessage',
            table='alumni_message',
        ),
        migrations.AlterModelTable(
            name='whystayconnected',
            table='why_stay_connected',
        ),
    ]
