# Generated by Django 5.2 on 2025-05-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_faculty_options_alter_faculty_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsItem',
            new_name='NewsEvents',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
