# Generated by Django 5.2 on 2025-05-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='dean/')),
                ('title', models.CharField(default='Dean of Students', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('office_address', models.TextField()),
                ('message_from_dean', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DeanStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='dean/staff/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
