# Generated by Django 5.2 on 2025-05-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_deanprofile_deanstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='deanprofile',
            name='short_description',
            field=models.TextField(default='', max_length=100),
        ),
    ]
