# Generated by Django 5.2 on 2025-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_deanprofile_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLeadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='student_leadership/')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
