# Generated by Django 5.2 on 2025-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_studentleadership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentleadership',
            name='short_description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
