# Generated by Django 5.2 on 2025-05-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_studentleadership_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentleadership',
            name='short_description',
        ),
    ]
