# Generated by Django 5.2 on 2025-05-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_studentleadership_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobsInternshipsAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('description', models.TextField(max_length=300)),
                ('link', models.URLField()),
            ],
        ),
    ]
