# Generated by Django 5.2 on 2025-05-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_club_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='image',
        ),
        migrations.CreateModel(
            name='SportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sports/')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.sport')),
            ],
        ),
    ]
