# Generated by Django 5.2 on 2025-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_dispensarycontact_dispensarygallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensaryservice',
            name='service_list',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
