# Generated by Django 5.2 on 2025-05-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_dispensaryservice_service_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensaryservice',
            name='service_list',
            field=models.CharField(blank=True),
        ),
    ]
