# Generated by Django 5.2 on 2025-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_cafeteriaimage_cafeteriamenu_cafeteriaservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeteriaMenuPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cafeteria_menus/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='file',
        ),
        migrations.RemoveField(
            model_name='cafeteriamenu',
            name='uploaded_at',
        ),
    ]
