# Generated by Django 5.2 on 2025-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(blank=True),
        ),
    ]
