# Generated by Django 5.2 on 2025-05-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_contactinfo_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinfo',
            old_name='address',
            new_name='contact_detail',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='website',
        ),
    ]
