# Generated by Django 5.2 on 2025-05-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_rename_address_contactinfo_contact_detail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='office_hours',
        ),
    ]
