# Generated by Django 5.2 on 2025-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_remove_contactinfo_office_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevents',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
