# Generated by Django 5.1.3 on 2025-06-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensaryservice',
            name='service_list',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
