# Generated by Django 5.1.3 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_logo_logo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_class', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Social Links',
                'db_table': 'social_links',
            },
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name_plural': 'Logo'},
        ),
        migrations.AlterModelTable(
            name='logo',
            table='logo',
        ),
    ]
