# Generated by Django 5.2 on 2025-06-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_sociallinks_alter_logo_options_alter_logo_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StaffMember',
            new_name='StaffLeadership',
        ),
    ]
