# Generated by Django 5.2 on 2025-06-10 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_rename_staffmember_staffleadership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutinfo',
            options={'verbose_name_plural': 'About Info'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='deanprofile',
            options={'verbose_name_plural': 'Dean Profile'},
        ),
        migrations.AlterModelOptions(
            name='dispensarygallery',
            options={'verbose_name_plural': 'Dispensary Gallery'},
        ),
        migrations.AlterModelOptions(
            name='jobsinternshipsads',
            options={'verbose_name_plural': 'Jobs & Internship Ads'},
        ),
        migrations.AlterModelOptions(
            name='newsevents',
            options={'verbose_name_plural': 'News & Events'},
        ),
        migrations.AlterModelOptions(
            name='staffleadership',
            options={'verbose_name_plural': 'Staff Leadership'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name_plural': 'Stats'},
        ),
        migrations.AlterModelOptions(
            name='studentleadership',
            options={'verbose_name_plural': 'Student Leadership'},
        ),
        migrations.AlterModelOptions(
            name='visionmission',
            options={'verbose_name_plural': 'Vision & Mission'},
        ),
        migrations.AlterModelOptions(
            name='whychooseus',
            options={'verbose_name_plural': 'Why Choose Us'},
        ),
    ]
